default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: To-Do-List-API_development
  username: kristiangolemi
  password: 

test:
  <<: *default
  database: To-Do-List-API_test

production:
  <<: *default
  database: To-Do-List-API_production
  username: todolistapi
  password: <%= ENV['TODOLISTAPI_DATABASE_PASSWORD'] %>
